# This is a basic workflow to help you get started with Actions

name: build and publish to gh-pages branch

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: build doc and push to github pages
        run: |
          pip3 install setuptools
          pip3 install teedoc
          ls -al ~/.local/bin/
          export PATH=~/.local/bin/:$PATH
          teedoc install
          teedoc build
          out_dir=out`python3 -c 'import json; f=open("site_config.json");config=json.load(f);path=config["site_root_url"] if config["site_root_url"].endswith("/") else config["site_root_url"][:-1];print(path)'`
          mkdir -p $out_dir/.github/workflows
          cp .github/workflows/* $out_dir/.github/workflows/
          cp CNAME $out_dir/CNAME
          cd $out_dir
          git init
          git config user.name ${{ secrets.GIT_NAME }}
          git config user.email ${{ secrets.GIT_EMAIL }}
          git remote add upstream "git@github.com:${{ secrets.REPO }}.git"
          git add -A
          git commit -m "rebuild website ad $GITHUB_REF"
          SSHPATH="$HOME/.ssh"
          rm -rf "$SSHPATH"
          mkdir -p "$SSHPATH"
          echo "${{ secrets.ACCESS_KEY }}" > "$SSHPATH/id_rsa"
          chmod 600 "$SSHPATH/id_rsa"
          sudo sh -c "echo StrictHostKeyChecking no >>/etc/ssh/ssh_config"
          git push upstream HEAD:gh-pages --force
          
          
